version: '3.8'

services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "5001:5000"
    environment:
      - PG_PASSWORD=PostgresSQLthomas1
      - DB_HOST=db
      - DB_NAME=cycling_buddy
      - DB_USER=postgres
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=cycling_buddy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=PostgresSQLthomas1
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d   # ← ADD THIS LINE

volumes:
  postgres_data:
